FROM mcr.microsoft.com/dotnet/aspnet:5.0

# install tooling necessary to get debugging working
RUN apt-get update
RUN apt-get install curl -y
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /app/vsdbg
RUN apt-get install openssh-server -y
RUN mkdir /run/sshd

# move various artifacts into the /app folder
COPY _artifacts /app/api
COPY automation/start.sh /start.sh
COPY _ssh /app/ssh

# configure SSH so that we can remote into container with the debugger
COPY automation/sshd_config /etc/ssh/sshd_config
RUN mkdir -p ~/.ssh
RUN chmod 600 ~/.ssh
RUN touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
# take the keyfile that we generated and place it in the authorized keys file
RUN cat app/ssh/debug.pub >> ~/.ssh/authorized_keys

RUN chmod 777 /start.sh
CMD /start.sh